#pragma once

#define IDI_MAIN_ICON   101

#define APP_VERSION_MAJOR 1
#define APP_VERSION_MINOR 4
#define APP_VERSION_PATCH 0
#define APP_VERSION_BUILD 0

#define APP_VERSION_FILE_STRING "1.4.0.0"
#define APP_VERSION_DISPLAY_STRING "1.4.0"
#define APP_VERSION_DISPLAY_STRING_W L"1.4.0"
